Database:
    DBType: mysql
    Username: root
    Password: asdfgh
    Host: 127.0.0.1:3306
    DBName: entrytask
    Charset: utf8mb4
    ParseTime: True
    MaxIdleConns: 10
    MaxOpenConns: 30

Redis:
    Host: 127.0.0.1:6379
    DBIndex: 0

Client:
    RPCHost: 127.0.0.1:8003
    connNum: 20

Server:
    RunMode: debug
    Host: localhost
    HttpPort: 8080
    RPCPort: 8003
    ReadTimeout: 60
    WriteTimeout: 60    